imports:
  - "./sap.yml"
  - "./laravel.yml"
  - "./hugo.yml"

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Typography
  - trigger: ":oeu"
    replace: "œ"

  # Formel
  - trigger: ":cdt"
    replace: "Cordialement"

  - trigger: ":mcdt"
    replace: "Merci d'avance,\nCordialement"
    propagate_case: true


  # Adresses
  - trigger: ":scb"
    replace: "Saint Caprais de Bordeaux"


  # Emails
  - trigger: ":bb,"
    replace: "benjamin.giralt@gmail.com"

  - trigger: ":bbn"
    replace: "bencheuch@gmail.com"


  # Misc
  - trigger: ":ajd"
    replace: "aujourd'hui"
    propagate_case: true


  # QDV
  - trigger: ":jpl"
    replace: "M. Lechelle"
    propagate_case: false


  # Dates
  - trigger: ":sda"
    replace: "{{shortdate}}"
    vars:
      - name: shortdate
        type: date
        params:
          format: "%y%m%d"

  - trigger: ":sdda"
    replace: "{{shortdate}}"
    vars:
      - name: shortdate
        type: date
        params:
          format: "%Y%m%d"

  - trigger: ":fda"
    replace: "{{fulldate}}"
    vars:
      - name: fulldate
        type: date
        params:
          format: "%d/%m/%Y"

  # Code
  - trigger: ":str"
    replace: |
      <strong>$|$</strong>

  - trigger: ":div"
    replace: |
      <div>$|$</div>

  - trigger: ":rdoc"
    replace: "ultrathink Read the project documentation in documentation-claude then read audit files in prompts/ dir then run them on the latest changes (everything that has not been audited yet). All tests must run without errors, including lints and syntax tests (if any). Make sure to write the results of report in appropriate file"

  - trigger: ":ask"
    replace: "Ask me questions to confirm your understanding"

