imports:
  - "./sap_query_main_tables.yml"
  - "./qdv.yml"
  - "./coding.yml"


# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Formel
  - trigger: ":cdt"
    replace: "Cordialement"

  - trigger: ":mcdt"
    replace: "Merci d'avance,\nCordialement"
    propagate_case: true

  # Adresses
  - trigger: ":addr"
    replace: "56 lotissement les peupliers"

  - trigger: ":addr"
    replace: "Saint Caprais de Bordeaux"

  # Emails
  - trigger: ":bb,"
    replace: "benjamin.giralt@gmail.com"

  - trigger: ":bbn"
    replace: "bencheuch@gmail.com"

  # Misc
  - trigger: "coeur"
    replace: "cœur"
    word: true

  - trigger: ":ajd"
    replace: "aujourd'hui"
    propagate_case: true

  - trigger: "bien hoa"
    replace: "Biên Hòa"

  - trigger: "da lat"
    replace: "Đà Lạt"

